# Generated by Django 2.2.2 on 2020-08-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200818_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='app.Subjects', verbose_name='选修课程'),
        ),
    ]
