# Generated by Django 2.2.2 on 2020-08-18 13:21

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200818_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.Students.get_photo, verbose_name='照片'),
        ),
    ]
